### ISSUE TITLE
Testing with CH32F103C8T6

### ISSUE THREAD

**Issue by ctaddey** [keirf/greaseweazle-firmware#3]
Currently there is no way to get hold of a genuine ST32 in my country. So I decided to try with a blue pill with CH32F103C8T6 chip.
http://www.wch-ic.com/products/CH32F103.html
I was able to upload the firmware to it, but it doesn't respond to GW info. However, if I put it in fimware update mode with the jumper, it does respond:

Host Tools: 1.9
Device:
  Port:     COM8
  Model:    Greaseweazle F1
  MCU:      72MHz, 20kB SRAM
  Firmware: 1.3 (Bootloader)
  Serial:   GW9858ABCD007BBC562000410F
  USB Rate: Full Speed (12 Mbit/s)

So I did the blinky test:
** Keir Fraser <keir.xen@gmail.com>
** https://github.com/keirf/Greaseweazle
Serial = abcd:9858:bc56:007b:410f:2000
Flash Size = 64kB (STM32F103x8 Medium-Density)
Device ID = 0x0410
Revision  = 0x2000
**WARNING**: Device returned valid IDCODE! Fake?
Testing I2C1... OK
Testing I2C2... OK
Testing SPI1... OK
Testing SPI2... OK
Testing TIM1... OK
Testing TIM2... OK
Testing TIM3... OK
Testing TIM4... OK
DMA Test #1... OK
DMA Test #2... OK
DMA Test #3... OK
DMA Test #4... OK
Testing 64kB Flash... **FAILED** [Exception #5]

This is my first experience with GW. So what does Exception #5 mean? Is it a hardware failure or maybe just incompatible chip? (Do I buy another one?)
Is there any further testing I can do?
Thank you.

**Comment by keirf** [comment]
BusFault. Probably this chip does not actually have 64kB Flash. It is not even a valid CH32F103C8 chip therefore.
