### ISSUE TITLE
Track0 signal asserted after seek to cylinder 1 - After update to v1.6. from v1.5

### ISSUE THREAD

**Issue by BlkRckZ28** [keirf/greaseweazle-firmware#6]
After updating to version 1.6 this morning, I can no longer write a disk image.
Command line and response:
gw write ".\DiskImages\blank180.img" --erase-empty --retries 0 --format ibm.180 --drive A --tracks h=0
Format ibm.180
Writing c=0-39:h=0
T0.0: Writing Track (Flux: 200.0ms period, 220.0 ms total, Terminate at index)
** FATAL ERROR:
Track0 signal asserted after seek to cylinder 1

Reverted back to v1.5 and the above command works fine.

**Comment by keirf** [comment]
Hi, Thanks for the report! Can you send the output of `gw info` and `gw delays`? Also, what model of disk drive are you using?

The new firmware has changed how post-seek delays are implemented, to make them asynchronous. That is, the command can return after the seek, before it has fully settled. The required further delay is added to the start of the *next* command, if it's still needed by then. Hence the tools now check the track-0 sensor earlier than they did before.

It's possible that the default track step time (10ms) is not enough for your drive, and you got away with it before. We should check the datasheet if it's available.

It is also possible there is a bug.

**Comment by BlkRckZ28** [comment]
gw info

Host Tools: 1.20

Device:

  Port:     COM4

  Model:    Greaseweazle V4.1

  MCU:      AT32F403A, 216MHz, 224kB SRAM

  Firmware: 1.6

  Serial:   GWB01431635976C010078D1705

  USB:      Full Speed (12 Mbit/s), 128kB Buffer

 

gw delays

Select Delay: 10us

Step Delay:   10000us

Settle Time:  15ms

Motor Delay:  750ms

Watchdog:     10000ms

Pre-Write:    100us

Post-Write:   1000us

Index Mask:   200us

 

The disk is a TEAC FD-50A-02-U.   Circa 1980’s. Very old.

Is there a command line parameter to override the default step time? Something I can try.

I believe you are correct in your assessment. These older drives aren’t exactly fast. I could also imagine 8in drives would be much worse because of the mass of the head and its mechanism.

 

Andy

**Comment by keirf** [comment]
Unfortunately I can't find a datasheet, but those were among the first drives made by TEAC. I would guess that they need a step delay of at least 20ms. Try this when you first connect your Greaseweazle:
```
gw delays --step 20000
```

**Comment by BlkRckZ28** [comment]
Yup… That worked.

Thanks for your help…

 

Probably worth noting somewhere, that this could happen to others and this solution.

I would imagine that there a LOT of users with older drives. The 8in drives would be significantly slower.

 

Maybe the default should be 20ms.

 

Andy

**Comment by keirf** [comment]
20ms sounds really bad with the more popular 3.5-inch drives, which can step in as little as 2ms. Some drives need as much as 30ms. So it's a bit of a tradeoff. I could make the error more useful. I will have it suggest both a "gw reset" and a "gw delays" solution.

**Comment by BlkRckZ28** [comment]
A useful ‘failure’ messages as you are suggesting would is a perfectly acceptable solution.

I like it !!!


Thanks for your help on this.

 

Andy
