### ISSUE TITLE
Error Compiling

### ISSUE THREAD

**Issue by xq1xq1xq1** [keirf/greaseweazle-firmware#9]
When I do the make from root of greaseweazle-firmware-1.6 I get this error:

```
make[4]: Entering directory '/root/DYMO_FREEDMO/00_greaseweazle-firmware-1.6/out/at32f4/prod/bootloader/mcu/at32f4'
CC fpec.o
../../../../../../src/mcu/at32f4/fpec.c:1:1: error: expected identifier or '(' before '.' token
    1 | ../stm32f1/fpec.c
      | ^
make[4]: *** [/root/DYMO_FREEDMO/00_greaseweazle-firmware-1.6/Rules.mk:98: fpec.o] Error 1
make[4]: Leaving directory '/root/DYMO_FREEDMO/00_greaseweazle-firmware-1.6/out/at32f4/prod/bootloader/mcu/at32f4'
make[3]: *** [/root/DYMO_FREEDMO/00_greaseweazle-firmware-1.6/Rules.mk:68: at32f4/build.o] Error 2
make[3]: Leaving directory '/root/DYMO_FREEDMO/00_greaseweazle-firmware-1.6/out/at32f4/prod/bootloader/mcu'
make[2]: *** [/root/DYMO_FREEDMO/00_greaseweazle-firmware-1.6/Rules.mk:68: mcu/build.o] Error 2
make[2]: Leaving directory '/root/DYMO_FREEDMO/00_greaseweazle-firmware-1.6/out/at32f4/prod/bootloader'
make[1]: *** [Makefile:36: target] Error 2
make[1]: Leaving directory '/root/DYMO_FREEDMO/00_greaseweazle-firmware-1.6'
make: *** [Makefile:17: prod-at32f4] Error 2

```

what do I need to to compile?

Thanks!

**Comment by keirf** [comment]
Try `make VERBOSE=1` so we can see the actual compilation commands being attempted.

**Comment by keirf** [comment]
Actually I don't think the checkout of the repository has worked properly. That's supposed to be a soft link (symlink) but looks like it's been interpreted literally.

**Comment by keirf** [comment]
Is this on Windows? I may be able to get rid of the symlink altogether.

**Comment by xq1xq1xq1** [comment]
I am making on Debian

**Comment by xq1xq1xq1** [comment]
What I am trying to is check if the STM32 I have is true or not and want to use Blinky

**Comment by keirf** [comment]
That's a strange build path on Linux, being under root. I suspect that the file that's failing to build is not correctly a symlink for some reason. I would check that.

**Comment by keirf** [comment]
If all you want is blinky, it's included in the firmware binary release which you can download via GitHub. Unzip the release and you will find the hex file under hex/alt.

**Comment by xq1xq1xq1** [comment]
okay - thanks - I also want to try your firmware as having issues with other dymo repository though

**Comment by xq1xq1xq1** [comment]
I uploaded the blinky firmware on Windows using the ST32 Programmer, verified and checksum went okay

I disconnected the BluePill from the programming software and the RED LED still stayed on SOLID

Am I correct to assume that I have a fake Bluepill?

**Comment by keirf** [comment]
Probably. You can check serial output on pin PA9 at 115200 baud to see what went wrong.

**Comment by xq1xq1xq1** [comment]
I'm new to this, any guidance on how to do that is appreciated

**Comment by keirf** [comment]
You probably programmed via a serial adapter and you can use the same to dump logs via the same serial pins on the blue pill. You would use a terminal program such as miniterm or minicom on the usb serial adapter's advertised serial/com port.

**Comment by keirf** [comment]
The original symlink issue is definitely fixed in master. No more symlinks in the build process.
